name: Unit test
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env
        with:
          install-dev: "true"
          extras: "--all-extras"

      - name: Run tests
        run: uv run pytest test